version: 0.2

env:
  #variables:
     # key: "value"
     # key: "value"
  parameter-store:
    PT_PROJECT: "/CodeBuild/homepage/PT_PROJECT"
    PT_TOKEN: "/CodeBuild/homepage/PT_TOKEN"
    GOOGLE_MAPS_API_KEY: "/CodeBuild/homepage/GOOGLE_MAPS_API_KEY"
    SENTRY_AUTH_TOKEN: "/CodeBuild/homepage/SENTRY_AUTH_TOKEN"
    SENTRY_ORG: "/CodeBuild/homepage/SENTRY_ORG"
    SENTRY_PROJECT: "/CodeBuild/homepage/SENTRY_PROJECT"
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - n 22
      - set
      - sysctl fs.inotify.max_user_watches
      - sysctl fs.inotify.max_user_watches=524288
      - sysctl fs.inotify.max_user_watches
  pre_build:
    commands:
      - chmod a+x -R bin/* scripts/*.sh
      - bin/codebuild-setup.sh
  build:
    commands:
      - set
      - bin/codebuild-test.sh
reports:
  coverage-report:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: 'COBERTURAXML'
artifacts:
  files:
    - '**/*'
  name: builds/$CODEBUILD_BUILD_NUMBER/coverage
  base-directory: coverage
cache:
  paths:
    - '/root/.npm/**/*'
