version: 0.2

env:
  parameter-store:
    PT_PROJECT: "/CodeBuild/homepage/PT_PROJECT"
    PT_TOKEN: "/CodeBuild/homepage/PT_TOKEN"
    GOOGLE_MAPS_API_KEY: "/CodeBuild/homepage/GOOGLE_MAPS_API_KEY"
    SENTRY_AUTH_TOKEN: "/CodeBuild/homepage/SENTRY_AUTH_TOKEN"
    SENTRY_ORG: "/CodeBuild/homepage/SENTRY_ORG"
    SENTRY_PROJECT: "/CodeBuild/homepage/SENTRY_PROJECT"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20
      - set
      - sysctl fs.inotify.max_user_watches
      - sysctl fs.inotify.max_user_watches=524288
      - sysctl fs.inotify.max_user_watches
  pre_build:
    commands:
      - chmod a+x -R bin/* scripts/*.sh
      - bin/codebuild-setup.sh
  build:
    commands:
      - set
      - npm run build
      - ls dist
  post_build:
    commands:
      if [ -f ./scripts/releaseNotes.sh ]; then ./scripts/releaseNotes.sh; fi
artifacts:
  files:
    - '**/*'
  name: homepage-build.zip
  base-directory: dist
