/* istanbul ignore file */
import BurtonThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/Burton_2016_03_crop-scaled.jpg';
import NapangardiThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/Napandardi_2013_40_crop_WEB.jpg';
import PetyarreThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/Petyarre_2001_02_crop_WEB.jpg';
import TjupurrulaThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/Tjupurrula_2014_40_WEB.jpg';
import Kunawarritji1Thumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/2018.27_Kunawarritji-1-landscape-2.jpg';
import Kunawarritji2Thumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/2018.28_Kunawarritji-2-landscape-2.jpg';
import PikkuwThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/UQAM_20241219_CampusArtwork_046.jpg';
import WhispersThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/UQAM_20260116_CampusArtwork_073_LR.jpg';
import WarualThumbnail from '../../../../../../public/images/artTrail/artwork/thumbs/Robinson_2017_02_WEBREADY.jpg';

export const ART_TRAIL_MAP_POIS = [
    {
        id: 'artwork-punu-tjukurpa',
        menuTitle: 'Hector Tjupuru Burton, Ray Ken, Mick Wikilyiri & Brenton Ken,',
        popupAriaLabel: 'Punu Tjukurpa, Duhig Tower, Level 1',
        popupDescription: '<em>Punu Tjukurpa</em> 2013',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: BurtonThumbnail,
        popupThumbnailAlt: 'Punu Tjukurpa artwork thumbnail',
        tableLinkText: 'Hector Tjupuru Burton, Ray Ken, Mick Wikilyiri and Brenton Ken, <em>Punu Tjukurpa</em>, 2013',
        trailStepIndex: 1,
        lng: 153.014414,
        lat: -27.496418,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-sand-hills',
        popupTitle: 'Lily Kelly Napangardi,',
        popupAriaLabel: 'Sand Hills, Duhig Tower, Level 1',
        popupDescription: '<em>Sand Hills</em> 2007',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: NapangardiThumbnail,
        popupThumbnailAlt: 'Sand Hills artwork thumbnail',
        tableLinkText: 'Lily Kelly Napangardi, <em>Sand Hills</em>, 2007',
        trailStepIndex: 2,
        lng: 153.0144104,
        lat: -27.4964431,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-devil-mountain-lizard-dreaming',
        popupTitle: 'Gloria Tamerre Petyarre,',
        popupAriaLabel: 'Devil Mountain Lizard Dreaming, Duhig Tower, Level 1',
        popupDescription: '<em>Devil Mountain Lizard Dreaming</em> 1997',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: PetyarreThumbnail,
        popupThumbnailAlt: 'Devil Mountain Lizard Dreaming artwork thumbnail',
        tableLinkText: 'Gloria Tamerre Petyarre, <em>Devil Mountain Lizard Dreaming</em>, 1997',
        trailStepIndex: 3,
        lng: 153.0144235,
        lat: -27.4964782,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-tingari-ceremonies',
        popupTitle: 'Johnny Yungut Tjupurrula,',
        popupAriaLabel: 'Tingari ceremonies at Wilkinkarra, Duhig Tower, Level 1',
        popupDescription: '<em>Tingari ceremonies at Wilkinkarra</em> 2003',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: TjupurrulaThumbnail,
        popupThumbnailAlt: 'Tingari ceremonies at Wilkinkarra artwork thumbnail',
        tableLinkText: 'Johnny Yungut Tjupurrula, <em>Tingari ceremonies at Wilkinkarra</em>, 2003',
        trailStepIndex: 4,
        lng: 153.01443,
        lat: -27.4965,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-nora-wompi-nungurrayi',
        menuTitle: 'Nora Wompi Nungurrayi,',
        menuDescription: '<em>Kunawarritji 1</em> and <em>Kunawarritji 2</em> 2012',
        popupTitle: 'Nora Wompi Nungurrayi,',
        popupAriaLabel: 'Kunawarritji 1, Duhig Tower, Level 2',
        popupDescription: '<em>Kunawarritji 1</em> 2012',
        popupLevelLabel: 'Duhig Tower, Level 2',
        popupThumbnailSrc: Kunawarritji1Thumbnail,
        popupThumbnailAlt: 'Kunawarritji 1 artwork thumbnail',
        tableLinkText: 'Nora Wompi Nungurrayi, <em>Kunawarritji 1 and Kunawarritji 2</em>, 2012',
        trailStepIndex: 5,
        lng: 153.01427,
        lat: -27.4966,
        zLevel: 1,
        color: '#51247a',
    },
    {
        id: 'artwork-nora-wompi-nungurrayi-2',
        popupTitle: 'Nora Wompi Nungurrayi,',
        popupAriaLabel: 'Kunawarritji 2, Duhig Tower, Level 2',
        popupDescription: '<em>Kunawarritji 2</em> 2012',
        popupLevelLabel: 'Duhig Tower, Level 2',
        popupThumbnailSrc: Kunawarritji2Thumbnail,
        popupThumbnailAlt: 'Kunawarritji 2 artwork thumbnail',
        trailStepIndex: 5,
        lng: 153.01426,
        lat: -27.49658,
        zLevel: 1,
        color: '#51247a',
    },
    {
        id: 'artwork-pikkuw',
        popupTitle: 'Craig Koomeeta,',
        popupAriaLabel: 'Pikkuw (Saltwater crocodile), Central Library, Level 1',
        popupDescription: '<em>Pikkuw (Saltwater crocodile)</em> 2008',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: PikkuwThumbnail,
        popupThumbnailAlt: 'Pikkuw artwork thumbnail',
        tableLinkText: 'Craig Koomeeta, <em>Pikkuw (Saltwater crocodile)</em>, 2008',
        trailStepIndex: 6,
        lng: 153.01398,
        lat: -27.49641,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-whispers',
        popupTitle: 'Megan Cope,',
        popupAriaLabel: 'Whispers (Poles), Central Library, Level 1',
        popupDescription: '<em>Whispers (Poles)</em> 2023',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: WhispersThumbnail,
        popupThumbnailAlt: 'Whispers artwork thumbnail',
        tableLinkText: 'Megan Cope, <em>Whispers (Poles)</em>, 2023',
        trailStepIndex: 7,
        lng: 153.013879,
        lat: -27.49634,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-whispers-2',
        popupTitle: 'Megan Cope,',
        popupAriaLabel: 'Whispers (Poles), Central Library, Level 1',
        popupDescription: '<em>Whispers (Poles)</em> 2023',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: WhispersThumbnail,
        popupThumbnailAlt: 'Whispers artwork thumbnail',
        trailStepIndex: 7,
        lng: 153.01378,
        lat: -27.49608,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-warual',
        popupTitle: 'Brian Robinson,',
        popupAriaLabel: 'Warual III, Central Library, Level 2',
        popupDescription: '<em>Warual III (Green Turtle)</em> 2015',
        popupLevelLabel: 'Central Library, Level 2',
        popupThumbnailSrc: WarualThumbnail,
        popupThumbnailAlt: 'Warual III artwork thumbnail',
        tableLinkText: 'Brian Robinson, <em>Warual III (Green Turtle)</em>, 2015',
        trailStepIndex: 8,
        lng: 153.013755,
        lat: -27.496184,
        zLevel: 1,
        color: '#51247a',
    },
];

export const getArtworkPoiById = id => ART_TRAIL_MAP_POIS.find(poi => poi.id === id) ?? {};
