export const allowedFileTypes = {
    'application/*': [
        '.pdf',
        '.zip',
        '.tar',
        '.gz',
        '.mxf',
        '.7z',
        '.rar',
        '.xls',
        '.xlsx',
        '.docx',
        '.pptx',
        '.ods',
        '.epub',
        '.fbx',
        '.json',
        '.obj',
        '.h5p',
        '.xml',
    ],
    'image/*': ['.jpeg', '.gif', '.tiff', '.png'],
    'video/*': ['.mkv', '.mov', '.mp4', '.mpg', '.avi', '.wmv'],
    'audio/*': ['.mp3', '.mpeg', '.wav', '.wav', '.wmv', '.wma', '.m4a'],
    'text/*': ['.csv', '.html'],
    'model/*': ['.obj'],
};
