export const allowedFileTypes = {
    'application/x-7z-compressed': ['.7z'],
    'application/vnd.rar': ['.rar'],
    'application/x-rar-compressed': ['.rar'],
    'application/zip': ['.zip', '.h5p', '.scorm'],
    'application/x-tar': ['.tar'],
    'application/gzip': ['.gz'],
    'application/x-gzip': ['.gz'],
    'application/mxf': ['.mxf'],
    'application/pdf': ['.pdf'],
    'application/vnd.ms-excel': ['.xls', '.xla', '.xlc', '.xlm', '.xlt', '.xlw'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': ['.pptx'],
    'application/vnd.oasis.opendocument.spreadsheet': ['.ods'],
    'application/epub+zip': ['.epub'],
    'application/json': ['.json', '.gsheet'],
    'application/xml': ['.xml'],
    'text/xml': ['.xml'],
    'application/octet-stream': ['.fbx', '.obj', '.stl'],
    'model/obj': ['.obj'],
    'model/stl': ['.stl'],
    'image/jpeg': ['.jpe', '.jpeg', '.jpg'],
    'image/gif': ['.gif'],
    'image/png': ['.png'],
    'image/tiff': ['.tif', '.tiff'],
    'video/x-matroska': ['.mkv', '.mks'],
    'video/x-matroska-3d': ['.mk3d'],
    'video/quicktime': ['.mov', '.qt'],
    'video/mp4': ['.mp4', '.mp4v'],
    'video/mpeg': ['.m1v', '.m2v', '.mpe', '.mpeg', '.mpg'],
    'video/x-msvideo': ['.avi'],
    'video/x-ms-wmv': ['.wmv'],
    'audio/mpeg': ['.mp3'],
    'audio/wav': ['.wav'],
    'audio/x-wav': ['.wav'],
    'audio/x-ms-wma': ['.wma'],
    'audio/mp4': ['.m4a'],
    'audio/x-m4a': ['.m4a'],
    'text/csv': ['.csv'],
    'text/html': ['.html'],
};
