export const allowedFileTypes = {
    'application/*': [
        '.7z',
        '.docx',
        '.epub',
        '.fbx',
        '.gsheet',
        '.gz',
        '.h5p',
        '.json',
        '.mxf',
        '.obj',
        '.ods',
        '.pdf',
        '.pptx',
        '.rar',
        '.scorm',
        '.stl',
        '.tar',
        '.xla',
        '.xlc',
        '.xlm',
        '.xls',
        '.xlsx',
        '.xlt',
        '.xlw',
        '.xml',
        '.zip',
    ],
    'image/*': ['.gif', '.jpe', '.jpeg', '.jpg', '.png', '.tif', '.tiff'],
    'video/*': [
        '.avi',
        '.m1v',
        '.m2v',
        '.mk3d',
        '.mks',
        '.mkv',
        '.mov',
        '.mp4',
        '.mp4v',
        '.mpe',
        '.mpeg',
        '.mpg',
        '.qt',
        '.wmv',
    ],
    'audio/*': ['.m4a', '.mp3', '.wav', '.wma'],
    'text/*': ['.csv', '.html', '.xml'],
    'model/*': ['.fbx', '.obj', '.stl'],
};
