export const ART_TRAIL_MAP_POIS = [
    {
        id: 'artwork-entry-1',
        popupTitle: 'Hector Tjupuru Burton, Ray Ken, Mick Wikilyiri & Brenton Ken,',
        popupDescription: '<em>Punu Tjukurpa</em> 2013',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/Burton_2016_03_crop-scaled.jpg',
        popupThumbnailAlt: 'Punu Tjukurpa artwork thumbnail',
        trailStepIndex: 1,
        lng: 153.014414,
        lat: -27.496418,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-2',
        popupTitle: 'Lily Kelly Napangardi,',
        popupDescription: '<em>Sand Hills</em> 2007',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/Napandardi_2013_40_crop_WEB.jpg',
        popupThumbnailAlt: 'Sand Hills artwork thumbnail',
        trailStepIndex: 2,
        lng: 153.0144104,
        lat: -27.4964431,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-3',
        popupTitle: 'Gloria Tamerre Petyarre,',
        popupDescription: '<em>Devil Mountain Lizard Dreaming</em> 1997',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/Petyarre_2001_02_crop_WEB.jpg',
        popupThumbnailAlt: 'Devil Mountain Lizard Dreaming artwork thumbnail',
        trailStepIndex: 3,
        lng: 153.0144235,
        lat: -27.4964782,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-4',
        popupTitle: 'Johnny Yungut Tjupurrula,',
        popupDescription: '<em>Tingari ceremonies at Wilkinkarra</em> 2003',
        popupLevelLabel: 'Duhig Tower, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/Tjupurrula_2014_40_WEB.jpg',
        popupThumbnailAlt: 'Tingari ceremonies at Wilkinkarra artwork thumbnail',
        trailStepIndex: 4,
        lng: 153.01443,
        lat: -27.4965,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-5a',
        popupTitle: 'Nora Wompi Nungurrayi,',
        popupDescription: '<em>Kunawarritji 1</em> and <em>Kunawarritji 2</em> 2012',
        popupLevelLabel: 'Duhig Tower, Level 2',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/2018.27_Kunawarritji-1-landscape-2.jpg',
        popupThumbnailAlt: 'Kunawarritji 1 artwork thumbnail',
        trailStepIndex: 5,
        lng: 153.01427,
        lat: -27.4966,
        zLevel: 1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-5b',
        popupTitle: 'Nora Wompi Nungurrayi,',
        popupDescription: '<em>Kunawarritji 1</em> and <em>Kunawarritji 2</em> 2012',
        popupLevelLabel: 'Duhig Tower, Level 2',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/2018.28_Kunawarritji-2-landscape-2.jpg',
        popupThumbnailAlt: 'Kunawarritji 2 artwork thumbnail',
        trailStepIndex: 5,
        lng: 153.01426,
        lat: -27.49658,
        zLevel: 1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-6',
        popupTitle: 'Craig Koomeeta,',
        popupDescription: '<em>Pikkuw (Saltwater crocodile)</em> 2008',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/UQAM_20241219_CampusArtwork_046.jpg',
        popupThumbnailAlt: 'Pikkuw artwork thumbnail',
        trailStepIndex: 6,
        lng: 153.01398,
        lat: -27.49641,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-7a',
        popupTitle: 'Megan Cope,',
        popupDescription: '<em>Whispers (Poles)</em> 2023',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/UQAM_20260116_CampusArtwork_073_LR.jpg',
        popupThumbnailAlt: 'Whispers artwork thumbnail',
        trailStepIndex: 7,
        lng: 153.013879,
        lat: -27.49634,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-7b',
        popupTitle: 'Megan Cope,',
        popupDescription: '<em>Whispers (Poles)</em> 2023',
        popupLevelLabel: 'Central Library, Level 1',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/UQAM_20260116_CampusArtwork_073_LR.jpg',
        popupThumbnailAlt: 'Whispers artwork thumbnail',
        trailStepIndex: 7,
        lng: 153.01378,
        lat: -27.49608,
        zLevel: -1,
        color: '#51247a',
    },
    {
        id: 'artwork-entry-8',
        popupTitle: 'Brian Robinson,',
        popupDescription: '<em>Warual III (Green Turtle)</em> 2015',
        popupLevelLabel: 'Central Library, Level 2',
        popupThumbnailSrc: '/images/artTrail/artwork/thumbs/Robinson_2017_02_WEBREADY.jpg',
        popupThumbnailAlt: 'Warual III artwork thumbnail',
        trailStepIndex: 8,
        lng: 153.013755,
        lat: -27.496184,
        zLevel: 1,
        color: '#51247a',
    },
];
